# Generated by Django 3.0.8 on 2020-07-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
